## Numpy 연습문제1

#### 1. np이름으로 numpy 패키지 가져오기

In [1]:
import numpy as np

#### 2. numpy 버전 출력하기

In [2]:
np.__version__

'1.26.4'

#### 3. 모두 0의 값을 갖는 사이즈가 10인 벡터 생성하기

In [5]:
vec1 = np.zeros(10, dtype=int)
vec1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. 값 10~49를 갖는 벡터 생성하기

In [6]:
vec2 = np.arange(10,50, dtype=int)
vec2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. 0~8 사이의 정수 값을 3X3 크기로 갖는 행렬 생성하기 

In [7]:
data1 = np.arange(0,9, dtype=int).reshape(3,3)
data1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. 실수 난수를 3X3X3의 크기로 갖는 배열 생성하기

In [8]:
data2 = np.random.rand(3,3,3)
data2

array([[[0.37777407, 0.20220816, 0.39620651],
        [0.02479593, 0.09698413, 0.8273006 ],
        [0.6001507 , 0.02121216, 0.48408679]],

       [[0.80233824, 0.91020405, 0.2924246 ],
        [0.23887534, 0.34523666, 0.28413775],
        [0.77038908, 0.97864869, 0.34105224]],

       [[0.51993678, 0.14338458, 0.20291942],
        [0.13729798, 0.01133075, 0.54915356],
        [0.00953298, 0.71149202, 0.67438841]]])