### Numpy 연습문제3

In [1]:
import numpy as np

### 연습문제. 마스크 인덱싱

In [2]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
data = np.random.randn(8,4)  # 표준정규분포난수

In [3]:
data

array([[ 0.21723605, -2.17925545, -0.62988567, -0.0608572 ],
       [ 0.54568189, -1.45243184,  0.96784915, -1.07591615],
       [ 1.46972498, -1.1919665 ,  0.72183261,  0.17915995],
       [ 1.20598396,  0.88496795, -0.08330231, -1.17250189],
       [ 0.05779614, -0.16376228,  0.43374601,  0.48468334],
       [ 2.05287061,  1.16734044,  0.20658539,  0.53228297],
       [-0.52803189, -0.08368893,  0.85070068,  0.67754697],
       [ 0.17631757, -0.94957268, -0.1278596 ,  1.43033751]])

#### 문제1. data array에서 0번째 열이 0보다 작은 행 데이터 가져오기

In [4]:
data[data[:,0]<0]

array([[-0.52803189, -0.08368893,  0.85070068,  0.67754697]])

#### 문제2. data array에서 0번째 열이 0보다 작은 행의 2, 3번째 열 데이터 가져오기

In [11]:
data[data[:,0]<0, 2:4]

array([[0.85070068, 0.67754697]])

----------------------------------------------

### 연습문제: 정렬

In [13]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

#### 문제1. 위 행렬에서 성적의 오름차순으로 학생의 이름을 출력하시오.

In [14]:
sort_idx = np.argsort(score_array)

In [15]:
name_array[sort_idx]

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

#### 문제2. 성적이 가장 좋은 사람의 이름을 출력하시오

In [18]:
i = np.argmax(score_array)
i

3

In [19]:
name_array[i]

'Kate'